foreground            #76d4e4
background            #101415
cursor                #aacdd3
selection_foreground  #101415
selection_background  #76d4e4

# Black
color0 #101415
color8 #3e494b

# Red
color1 #ffb4ab
color9 #ffb4ab

# Green
color2 #76d4e4
color10 #76d4e4

# Yellow
color3 #ffb785
color11 #ffb785

# Blue
color4 #aacdd3
color12 #aacdd3

# Magenta
color5 #76d4e4
color13 #76d4e4

# Cyan
color6 #ffb785
color14 #ffb785

# White
color7 #dfe3e4
color15 #bdc9cb
