foreground            #79ddeb
background            #0f1415
cursor                #a8cdd3
selection_foreground  #0f1415
selection_background  #79ddeb

# Black
color0 #0f1415
color8 #3e494a

# Red
color1 #ffb4ab
color9 #ffb4ab

# Green
color2 #79ddeb
color10 #79ddeb

# Yellow
color3 #ffc199
color11 #ffc199

# Blue
color4 #a8cdd3
color12 #a8cdd3

# Magenta
color5 #79ddeb
color13 #79ddeb

# Cyan
color6 #ffc199
color14 #ffc199

# White
color7 #dfe3e4
color15 #bdc9cb
