# btop configuration file
# Generated to use Matugen theme

color_theme = "matugen.theme"
theme_background = False
truecolor = True
force_tty = False
presets = "cpu:0:default,mem:0:default,net:0:default,proc:0:default"
vim_keys = True
rounded_corners = True
graph_symbol = "braille"
graph_symbol_cpu = "default"
graph_symbol_mem = "default"
graph_symbol_net = "default"
graph_symbol_proc = "default"
shown_boxes = "cpu mem net proc"
update_ms = 1500
proc_sorting = "cpu lazy"
proc_reversed = False
proc_tree = False
proc_colors = True
proc_gradient = True
proc_per_core = False
proc_mem_bytes = True
proc_cpu_graphs = True
cpu_bottom = False
cpu_combined = False
cpu_single_graph = False
cpu_percentages = True
check_temp = True
cpu_sensor = "Auto"
show_battery = True
selected_battery = "Auto"
log_level = "WARNING"
