[config]
default_mode = "dark"
post_command = "~/.config/matugen/scripts/refresh.sh"

[templates]
hyprland = { input_path = "~/.config/matugen/templates/hyprland/colors.conf", output_path = "~/.config/hypr/colors.conf" }
waybar = { input_path = "~/.config/matugen/templates/waybar/style.css", output_path = "~/.config/waybar/style.css" }
wofi = { input_path = "~/.config/matugen/templates/wofi/style.css", output_path = "~/.config/wofi/style.css" }
wofi_powermenu = { input_path = "~/.config/matugen/templates/wofi/powermenu.css", output_path = "~/.config/wofi/powermenu.css" }
kitty = { input_path = "~/.config/matugen/templates/kitty/colors.conf", output_path = "~/.config/kitty/colors.conf" }
swaync = { input_path = "~/.config/matugen/templates/swaync/style.css", output_path = "~/.config/swaync/style.css" }
btop = { input_path = "~/.config/matugen/templates/btop/matugen.theme", output_path = "~/.config/btop/themes/matugen.theme" }
clipse = { input_path = "~/.config/matugen/templates/clipse/custom_theme.json", output_path = "~/.config/clipse/custom_theme.json" }
