###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

# Set programs that you use
$terminal = kitty
$browser = google-chrome-stable
$fileManager = nautilus
$menu = wofi --show drun
